---
title: "Output"
author: "Lucien Baumgartner"
date: "11/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

rm(list=ls())
setwd('~/ddj18/res/')

# import data and coerce column names to lower case characters
brutto <- read.csv("KANTON_ZUERICH_413.csv", stringsAsFactors=FALSE, sep=";") %>% 
  setNames(., tolower(names(.)))
sfin <- read.csv("KANTON_ZUERICH_434.csv", stringsAsFactors=FALSE, sep=";") %>% 
  setNames(., tolower(names(.)))
tax <- read.csv("KANTON_ZUERICH_68.csv", stringsAsFactors=FALSE, sep=";") %>% 
  setNames(., tolower(names(.)))

str(brutto)
str(sfin)
str(tax)

# subset, etc. 
brutto <- select(brutto, -c(thema_name:indikator_name, einheit_kurz:x)) %>% # get rid of non-unique columns which also do not confer any vital information
  rename(pubfinbrutto_value=indikator_value, # rename the indicator value in each dataset (see below; analoguous code); give it a unique name
         jahr=indikator_jahr) %>% # rename the year-join
  filter(bfs_nr > 0 &  jahr < 2017) # subset data accroding to your criteria
  
sfin <- select(sfin, -c(thema_name:indikator_name, einheit_kurz:x)) %>% 
  rename(sfin_value=indikator_value,
         jahr=indikator_jahr) %>% 
  filter(bfs_nr > 0 &  jahr < 2017)
  
tax <- select(tax, -c(thema_name:indikator_name, einheit_kurz:x)) %>% 
  rename(tax_value=indikator_value,
         jahr=indikator_jahr) %>% 
  filter(bfs_nr > 0 &  jahr < 2017)

# data now looks like that:
str(brutto)
str(sfin)
str(tax)

# as you can see, the tax dataframe has less rows than the other two
# this will generate NAs in the merged dataframe, for all the observations we do not have data for
sapply(ls(), function(x) dim(eval(parse(text=x))))

# before we join we have a look at the joins, to see whether they do indeed correspond or not
lapply(ls(), function(x){
  temp <- eval(parse(text=x))
  list(unique(temp$bfs_nr), unique(temp$gebiet_name), unique(temp$jahr))
  }) 

# the years and befs_nr seem to match, but if you compare the gebiet_name you'll see that different time periods are specified
# so we need to get rid of those using regular expressions
brutto <- mutate(brutto, gebiet_name=gsub('\\s\\(.*\\)$', '', gebiet_name))
sfin <- mutate(sfin, gebiet_name=gsub('\\s\\(.*\\)$', '', gebiet_name))
tax <- mutate(tax, gebiet_name=gsub('\\s\\(.*\\)$', '', gebiet_name))

# looks better now:
temp <- lapply(ls(), function(x) unique(eval(parse(text=x))$gebiet_name))
temp
identical(temp[[1]], temp[[2]]) & identical(temp[[2]], temp[[3]])
rm(temp)

# join data
df <- left_join(brutto, sfin, by = c("bfs_nr", "gebiet_name", "jahr")) %>% 
  left_join(., tax, by = c("bfs_nr", "gebiet_name", "jahr")) %>% 
  as_tibble
df
save(df, file='merged-data-benjamin-conservative.RDS')
load('merged-data-benjamin-conservative.RDS')
dim(df) 

# we see that there is no increase in rows, just in number of variables (all unique variables have been joined to the brutto dataframe)

# your merged dataset contains NA in the tax value column for the following observations
# ==(Illnau-Effretikon, Bauma, and Wiesendangen HAVE DIFFERENT bfs_numbers in the tax data set!!!!!)
filter(df, is.na(tax_value)) %>% print(n=400)


# so if you wanna have a dataset, which is merged irrespective of bfs_number, You just drop in its function as a second join
# join data
df <- left_join(brutto, sfin, by = c("bfs_nr", "gebiet_name", "jahr")) %>% 
  left_join(., select(tax, -bfs_nr), by = c("gebiet_name", "jahr")) %>% 
  as_tibble
df
save(df, file='merged-data-benjamin-lax.RDS')
load('merged-data-benjamin-lax.RDS')
dim(df) 

filter(df, is.na(tax_value)) %>% print(n=400)


```

